In [1]:
import pandas as pd
import numpy as np

In [2]:
sites_data_1 = pd.read_csv("~data/sites_data_s2_grid_index_update_1.csv")
sites_data_2 = pd.read_csv("~data/sites_data_s2_grid_index_update_2.csv")
sites_data_3 = pd.read_csv("~data/sites_data_s2_grid_index_update_3.csv")
sites_data_4 = pd.read_csv("~data/sites_data_s2_grid_index_update_4.csv")
sites_data_5 = pd.read_csv("~data/sites_data_s2_grid_index_update_5.csv")

In [3]:
pd_list = [sites_data_1, sites_data_2, sites_data_3, sites_data_4, sites_data_5]
sites_data = pd.concat(pd_list)

In [6]:
sites_data

,Unnamed: 0.1,Unnamed: 0,time,lat,lon,TUR,SPM,CHL,site,grid_index,grid_index_new
0,0,0,2020-01-04,52.655093,1.733927,75.791490,57.119390,10.334003,ukh1303-10400,2571,21
1,1,1,2020-01-04,52.655093,1.735674,75.522590,58.450360,9.273168,ukh1303-10400,2572,22
2,2,2,2020-01-04,52.655093,1.737421,69.529670,52.376694,9.113760,ukh1303-10400,2573,23
3,3,3,2020-01-04,52.655093,1.739168,65.611430,48.540340,8.395749,ukh1303-10400,2574,24
4,4,4,2020-01-04,52.655093,1.740915,66.520600,49.696520,7.250048,ukh1303-10400,2574,25
...,...,...,...,...,...,...,...,...,...,...,...
24225833,134225833,134225833,2022-12-29,52.546759,1.770615,48.331380,37.388218,5.401901,ukh1303-10650,47,2597
24225834,134225834,134225834,2022-12-29,52.546759,1.772362,53.736130,42.052635,5.581755,ukh1303-10650,48,2598
24225835,134225835,134225835,2022-12-29,52.546759,1.774109,54.029140,41.245102,5.807971,ukh1303-10650,48,2599
24225836,134225836,134225836,2022-12-29,52.546759,1.775856,52.296604,39.743805,5.866353,ukh1303-10650,50,2600
24225837,134225837,134225837,2022-12-29,52.546759,1.777603,50.219290,38.018670,5.678284,ukh1303-10650,51,2601

:

In [5]:
sites_data.to_csv('~data/sites_data_s2_grid_index_updated.csv')